---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-knife-deployment
  labels:
    app: app-knife
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-knife
  template:
    metadata:
      labels:
        app: app-knife
    spec:
      containers:
      - image: artifactory.raiffeisen.ru/container-training-docker/ctr-app-knife
        name: app
        env: #TODO configure env vars from secrets and confmaps too
        volumeMounts:
          - name: config
            mountPath: /usr/src/app/config
      volumes:
        - name: config
          configMap:
            name: training-configuration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-butter-deployment
  labels:
    app: app-butter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-butter
  template:
    metadata:
      labels:
        app: app-butter
    spec:
      containers:
      - image: artifactory.raiffeisen.ru/container-training-docker/ctr-app-butter
        name: app
        ports:
        - containerPort: 8080
